[package]
name = "Projet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
tokio = { version = "1.46.1", features = ["full"] }
tokio-udev = "0.9.1"
tokio-stream = "0.1.17"
users = "0.11"
nix = { version = "0.30.1", features = ["sched", "mount", "fs", "user"] }
caps = "0.5.5"
